package com.example.qweather.domain.dto.forecast

data class DailyWeatherDto(
    val clouds: Int,
    val date: String,
    val feelsLikeDay: Double,
    val feelsLikeEve: Double,
    val feelsLikeMorn: Double,
    val feelsLikeNight: Double,
    val feelsLikeUnit: String,
    val humidity: Double,
    val humidityMin: String,
    val humidityUnit: String,
    val pop: Int,
    val pressure: Int,
    val pressureUnit: String,
    val rain: Int,
    val rainUnit: String,
    val sunrise: Int,
    val sunset: Int,
    val temperature: Double,
    val temperatureEve: Double,
    val temperatureMax: Double,
    val temperatureMin: Double,
    val temperatureMorn: Double,
    val temperatureNight: Double,
    val temperatureUnit: String,
    val timestamp: Double,
    val weatherIcon: String,
    val weatherType: String,
    val weatherTypeAr: String,
    val windDirection: Int,
    val windSpeed: Double,
    val windSpeedUnit: String
)
